### ISSUE TITLE
Create an Email Dashboard

### ISSUE THREAD

**Issue by Shriukan33** [transport-nantes/tn_web#633] opened 2022-04-06 15:29 UTC
This dashboard must contain the following pieces of information : 
* Spending day
* Number of emails in queue for sending
* Number of already sent email
* Number of bounces
* Number of openings
* Number of clicks on content (CTA, Images, see on web link)
* Number of clicks on unsub link
* Number of unsub that were confirmed

**Comment by JeffAbrahamson** [comment] 2023-01-24 07:26
Closing as duplicate of #870.

**Closed by JeffAbrahamson** 2023-01-24 07:26 UTC
